/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_instasketch_instasketch_fragments_DatabaseFragment */

#ifndef _Included_io_github_instasketch_instasketch_fragments_DatabaseFragment
#define _Included_io_github_instasketch_instasketch_fragments_DatabaseFragment
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     io_github_instasketch_instasketch_fragments_DatabaseFragment
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL
        Java_io_github_instasketch_instasketch_fragments_DatabaseFragment_getMat(JNIEnv *env,
                                                                                 jobject instance,
                                                                                 jlong emptyMatAddr);

#ifdef __cplusplus
}
#endif
#endif